### ISSUE TITLE
Comfy got an update and the Vid2Vid wont work on it!

### ISSUE THREAD

**Issue by p0mad** [sylym/comfy_vid2vid#12]
Hi, Please update the Repo to be compatible with the new Comfy!

**Comment by p0mad** [comment]
### Loading: ComfyUI-Manager (V0.26.2)
### ComfyUI Revision: 1345 [a57b0c79]
Traceback (most recent call last):
  File "/home/jovyan/workspace/Control/nodes.py", line 1694, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/sd.py", line 3, in <module>
    from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_unet, model_lora_keys_clip
ImportError: cannot import name 'model_lora_keys_unet' from 'comfy.sd' (/home/jovyan/workspace/Control/comfy/sd.py)

Cannot import /home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid module for custom nodes: cannot import name 'model_lora_keys_unet' from 'comfy.sd' (/home/jovyan/workspace/Control/comfy/sd.py)

**Comment by p0mad** [comment]
@sylym @rttt1093

**Comment by Ferniclestix** [comment]
yep, she needs a fixin

**Comment by alexbofa** [comment]
Hello, yes, the same problem

**Comment by alexbofa** [comment]
Fix: https://github.com/sylym/comfy_vid2vid/pull/13

**Comment by p0mad** [comment]
@alexbofa 
Traceback (most recent call last):
  File "/home/jovyan/workspace/Control/nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/sd.py", line 9, in <module>
    from .convert_from_ckpt import convert_unet_checkpoint
  File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/convert_from_ckpt.py", line 1, in <module>
    from .tuneavideo.models.unet import UNet3DConditionModel
  File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/tuneavideo/models/unet.py", line 12, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
ModuleNotFoundError: No module named 'diffusers'

Cannot import /home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid module for custom nodes: No module named 'diffusers'

**Comment by alexbofa** [comment]
> @alexbofa Traceback (most recent call last): File "/home/jovyan/workspace/Control/nodes.py", line 1698, in load_custom_node module_spec.loader.exec_module(module) File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/**init**.py", line 8, in from .sd import load_checkpoint_guess_config, load_lora_for_models File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/sd.py", line 9, in from .convert_from_ckpt import convert_unet_checkpoint File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/convert_from_ckpt.py", line 1, in from .tuneavideo.models.unet import UNet3DConditionModel File "/home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid/tuneavideo/models/unet.py", line 12, in from diffusers.configuration_utils import ConfigMixin, register_to_config ModuleNotFoundError: No module named 'diffusers'
> 
> Cannot import /home/jovyan/workspace/Control/custom_nodes/comfy_vid2vid module for custom nodes: No module named 'diffusers'

See [that](https://github.com/sylym/comfy_vid2vid#:~:text=Next%2C%20download%20dependencies%3A)

Change on your path:
`"E:\ComfyUI\python_embeded\python.exe" "E:\ComfyUI\python_embeded\Scripts\pip.exe" install diffusers[torch]==0.11.1`
