### ISSUE TITLE
Why doesn't the custom node appear after I install the plugin?

### ISSUE THREAD

**Issue by shushu97** [sylym/comfy_vid2vid#14]
![1](https://github.com/sylym/comfy_vid2vid/assets/88243385/d4cb03d5-260b-480e-9e63-54bc053d666e)
![2](https://github.com/sylym/comfy_vid2vid/assets/88243385/592a8aef-006d-4f42-b612-42603567f32a)
![3](https://github.com/sylym/comfy_vid2vid/assets/88243385/b3540c35-d269-4f49-b430-f95ffa890ebb)

**Comment by brand-brothers** [comment]
Same issue here, did the install from the manager, then from the command line... No luck !

**Comment by levaleureux** [comment]
Exactly same issue I install it from the manager

**Comment by MangoTreasure** [comment]
Same Issue, anyone find the solve? or an alternative custom node set?

**Comment by 3illd** [comment]
Ditto.  Installed by cloning and also via Manager.  pip installed the requirements.txt for the project and I still get the errors.  Any advice?

**Comment by Kowala-San** [comment]
Same issue here is where it breaks for me:

**Traceback (most recent call last):
  File "C:\Users\josep\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\josep\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "C:\Users\josep\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid\sd.py", line 3, in <module>
    from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_unet, model_lora_keys_clip
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\josep\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)

_Cannot import C:\Users\josep\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (C:\Users\josep\Downloads\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy\sd.py)_**


Seems like itd be an awesome plugin hope its fix soon 

Thank you for your work

**Comment by mancat49** [comment]
Same issue.

**Comment by huwhitememes** [comment]
Same issue. Will the author share their thoughts? Anyone?

**Comment by flynet** [comment]
Solution here https://github.com/sylym/comfy_vid2vid/issues/16
