### ISSUE TITLE
Vid2Vid won't launch

### ISSUE THREAD

**Issue by Duemellon** [sylym/comfy_vid2vid#15]
I get a few messages:

_**I get this (probably unrelated)**_
D:\DProgram Files\Python\Python310\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:65: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'CPUExecutionProvider'
  warnings.warn(
Could not find efficiency nodes

**_Then this:_**
Traceback (most recent call last):
  File "E:\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 8, in <module>
    from .sd import load_checkpoint_guess_config, load_lora_for_models
  File "E:\ComfyUI\custom_nodes\comfy_vid2vid\sd.py", line 3, in <module>
    from comfy.sd import load_model_weights, ModelPatcher, VAE, CLIP, model_lora_keys_unet, model_lora_keys_clip
ImportError: cannot import name 'ModelPatcher' from 'comfy.sd' (E:\ComfyUI\comfy\sd.py)

**_Next this_**
Cannot import E:\ComfyUI\custom_nodes\comfy_vid2vid module for custom nodes: cannot import name 'ModelPatcher' from 'comfy.sd' (E:\ComfyUI\comfy\sd.py)
E:\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
E:\ComfyUI\web\extensions\failfast-comfyui-extensions
Total VRAM 12288 MB, total RAM 16172 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.

**_Finally this_**
   0.0 seconds (IMPORT FAILED): E:\ComfyUI\custom_nodes\comfy_vid2vid
   
   If there's some lines in some code I'm supposed to update please be specific to the filename & place to update. I see other people with similar errors but not the same so I'm not sure if they're related. I do have FFMPEG installed on the system & it is on the PATH properly.

**Comment by alexbofa** [comment]
Fix: https://github.com/sylym/comfy_vid2vid/pull/13
