### ISSUE TITLE
Erro when startup comfyui

### ISSUE THREAD

**Issue by arjanMeerten** [sylym/comfy_vid2vid#2]
I get this error after I installed it and startup comfyUI

`Traceback (most recent call last):
  File "C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\nodes.py", line 1093, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 8, in <module>    from .sd import load_checkpoint_guess_config
  File "C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\custom_nodes\comfy_vid2vid\sd.py", line 3, in <module>
    from comfy.sd import load_torch_file, load_model_weights, ModelPatcher, VAE, CLIP
ImportError: cannot import name 'load_torch_file' from 'comfy.sd' (C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\comfy\sd.py)`

**Comment by arjanMeerten** [comment]
I updated comfy and and this and now I get this error:

`Traceback (most recent call last):
  File "C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\nodes.py", line 1094, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\custom_nodes\comfy_vid2vid\__init__.py", line 14, in <module>
    from .train_tuneavideo import train
  File "C:\WorkingFiles\ML\StableDiffusion\GitRepos\ComfyUI\custom_nodes\comfy_vid2vid\train_tuneavideo.py", line 23, in <module>
    logger = get_logger(__name__, log_level="INFO")
TypeError: get_logger() got an unexpected keyword argument 'log_level'`

**Comment by sylym** [comment]
I have updated comfyui to the latest version, but I haven't encountered this issue. 
However, in the [latest update](https://github.com/sylym/comfy_vid2vid/commit/24266cc4ef71a66ae8ea9cea5ca6e9351ceb614e), I deleted this piece of code. You can update the code of the comfy_vid2vid library to the latest version and run it to see if any other issues arise.

**Comment by arjanMeerten** [comment]
I updated comfy and this one and it works great now, thanks!
